###
GET http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

###
GET http://127.0.0.1:8000/sentence/2
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

###
POST http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

{
  "file": 70,
  "src_str": "Tôi yêu em",
  "tar_str": "I love you",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}
###
POST http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

{
  "file": 70,
  "src_str": "Tôi yêu em"
}

###
PUT http://127.0.0.1:8000/sentence/1/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

{
  "file": 70,
  "src_str": "Tôi yêu em 2",
  "tar_str": "I love you 2",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}

###
DELETE http://127.0.0.1:8000/sentence/3/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
