
# SIGN UP
POST http://127.0.0.1:8000/sign_up/ 
Content-Type: application/json

{
    "username": "chi",
    "email": "chi@gmail.com",
    "password": "123456789"
}

###
# SIGN IN
POST http://127.0.0.1:8000/get-token/ 
Content-Type: application/json


{
    "username": "chi",
    "password": "123456789"
}
