###
GET http://103.90.228.121:8000/glossary_with_child/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

###
GET http://103.90.228.121:8000/glossary/?user_id=1
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

###
GET http://103.90.228.121:8000/glossary_with_child/2
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

###
POST http://103.90.228.121:8000/glossary/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "name": "Uncategory 10",
  "description": "Chưa phân nhóm",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
  "gloss_type": [4]
}

###
PUT http://103.90.228.121:8000/glossary/2/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "name": "khxhnv",
  "description": "Sản phẩm của trường ĐH Khoa học xhnv",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
  "gloss_type": [4,6]
}

###
DELETE http://103.90.228.121:8000/glossary/3/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3
