###
GET http://103.90.228.121:8000/sentence/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

###
GET http://103.90.228.121:8000/sentence/2
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

###
POST http://103.90.228.121:8000/sentence/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "file": 70,
  "src_str": "Tôi yêu em",
  "tar_str": "I love you",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}
###
POST http://103.90.228.121:8000/sentence/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "file": 70,
  "src_str": "Tôi yêu em"
}

###
PUT http://103.90.228.121:8000/sentence/45/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "file": 85,
  "src_str": "Tôi yêu em 2",
  "tar_str": "I love you 2",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}

###
DELETE http://103.90.228.121:8000/sentence/3/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3
