###
# Get all translation_memory
GET http://103.90.228.121:8000/translation_memory/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3
###
# Get all translation_memory of user_id
GET http://103.90.228.121:8000/translation_memory/?user_id=1
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3
###
# Get translation_memory id = 1
GET http://103.90.228.121:8000/translation_memory/1
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3
###
# Create a translation_memory
POST http://103.90.228.121:8000/translation_memory/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "name": "Default translation memory 2",
  "description": "Đây là TM mặc định, bất kỳ ai cũng có thể truy cập",
  "src_lang": "English",
  "tar_lang": "Vietnamese",
  "user": 1
}

###
# Update a translation_memory
PUT http://103.90.228.121:8000/translation_memory/3/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3

{
  "name": "TM3 updated",
  "description": "des updated",
  "src_lang": "phil",
  "tar_lang": "en",
  "user": 1
}

###
# Delete a translation_memory
DELETE http://103.90.228.121:8000/translation_memory/13/
Content-Type: application/json
Authorization: token ed947616967b148feda2126f9ee234f159252fc3



########################################################
