
# Delete index in elastic search
# curl -X DELETE 'http://localhost:9201/translation_memory'

###

GET http://localhost:9201/translation_memory/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "src_sentence": "Love in your eyes"
    }
  }
}

###

GET http://localhost:9201/translation_memory/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match": {"src_sentence": "Love in your eyes"} },
        { "terms": {"translation_memory.id":  [1,2]} }
      ]
    }
  }
}
###

GET http://localhost:9201/translation_memory/_count

###

GET http://localhost:9201/glossary/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match": {"src_phrase": "hoang trung chinh Google was founded in September 1998."} },
        { "terms": { "glossary.id": [1, 2] }}
      ]
    }
  }
}
###