
# Delete index in elastic search
# curl -X DELETE 'http://localhost:9200/translation_memory'

###

GET http://localhost:9200/translation_memory/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "src_sentence": "Love in your eyes"
    }
  }
}

###

GET http://localhost:9200/translation_memory/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match": {"src_sentence": "Love in your eyes"} },
        { "match": {"translation_memory.id":  1} }
      ]
    }
  }
}
###

GET http://localhost:9200/translation_memory/_count
