###
GET http://127.0.0.1:8000/glossary_Type/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

###
GET http://127.0.0.1:8000/glossary_Type/2
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

###
POST http://127.0.0.1:8000/glossary_Type/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

{
  "name": "Khoa học",
  "description": "bao gồm tất cả các thuật ngữ thuộc lĩnh vực Khoa học"
}

###
PUT http://127.0.0.1:8000/glossary_Type/2/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732

{
  "name": "Lâm nghiệp",
  "description": "bao gồm tất cả các thuật ngữ thuộc lĩnh vực Lâm nghiệp"
}

###
DELETE http://127.0.0.1:8000/glossary_Type/3/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
