
###
POST http://127.0.0.1:8000/glossary_content/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

{
  "src_phrase": "I love you",
  "tar_phrase": "Anh yêu em",
  "glossary": 1
}

###
GET http://127.0.0.1:8000/glossary_content/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

###
GET http://127.0.0.1:8000/glossary_content/2
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

###
PUT http://127.0.0.1:8000/glossary_content/1/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

{
  "src_phrase": "I love you so much",
  "tar_phrase": "Anh yêu em rất nhiều",
  "glossary": 1
}

###
DELETE http://127.0.0.1:8000/glossary_content/2/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0
