###
GET http://127.0.0.1:8000/glossary_with_child/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

###
GET http://127.0.0.1:8000/glossary/?user_id=1
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

###
GET http://127.0.0.1:8000/glossary_with_child/2
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

###
POST http://127.0.0.1:8000/glossary/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "Uncategory 10",
  "description": "Chưa phân nhóm",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
  "gloss_type": [4]
}

###
PUT http://127.0.0.1:8000/glossary/2/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "khxhnv",
  "description": "Sản phẩm của trường ĐH Khoa học xhnv",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
  "gloss_type": [4,6]
}

###
DELETE http://127.0.0.1:8000/glossary/3/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
