
GET http://127.0.0.1:8000/machine_translate/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA5MzExNjI5LCJqdGkiOiI4ZTExODMzNTBkMWU0YzA2YWUwYjAyNzIzMThjNTgxYSIsInVzZXJfaWQiOjF9.2jLhEoRRqFQU5gSMcQLKRfNFqvIG3kzSMs9_nRRwRFI

{
  "src_lang": "en",
  "tar_lang": "vi",
  "sentence": "I love you and you are mine",
  "service": ["gt", "mm", "onmt"]
}

###

GET http://127.0.0.1:8000/machine_translate/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA5MzExNjI5LCJqdGkiOiI4ZTExODMzNTBkMWU0YzA2YWUwYjAyNzIzMThjNTgxYSIsInVzZXJfaWQiOjF9.2jLhEoRRqFQU5gSMcQLKRfNFqvIG3kzSMs9_nRRwRFI

{
  "src_lang": "vi",
  "tar_lang": "en",
  "sentence": "Tuy trời mưa nhưng tôi vẫn đi học",
  "service": ["gt", "mm", "onmt"]
}

###