
###
POST http://127.0.0.1:8000/project/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "pj1",
  "user": 1,
  "src_lang": "en",
  "tar_lang": "vi",
  "translate_service": "GG",
  "translation_memory": [1],
  "glossary": [1]
}

###
GET http://127.0.0.1:8000/project/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

###
GET http://127.0.0.1:8000/project/?user_id=1
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
###
GET http://127.0.0.1:8000/project/2
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

###
PUT http://127.0.0.1:8000/project/2/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "pj1 updated",
  "user": 1,
  "src_lang": "vi",
  "tar_lang": "en",
  "translate_service": "GG",
  "translation_memory": [1],
  "glossary": [1]
}


###
DELETE http://127.0.0.1:8000/project/2/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
