###
GET http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

###
GET http://127.0.0.1:8000/sentence/2
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

###
POST http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

{
  "file": 70,
  "src_str": "Tôi yêu em",
  "tar_str": "I love you",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}
###
POST http://127.0.0.1:8000/sentence/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

{
  "file": 70,
  "src_str": "Tôi yêu em"
}

###
PUT http://127.0.0.1:8000/sentence/45/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0

{
  "file": 85,
  "src_str": "Tôi yêu em 2",
  "tar_str": "I love you 2",
  "score": 25,
  "is_confirmed": "False",
  "tag": "ok"
}

###
DELETE http://127.0.0.1:8000/sentence/3/
Content-Type: application/json
Authorization: token 13176ad6710547efae340cc356b9374012c092d0
