for i in {1..100}; do
curl -iX GET 'http://127.0.0.1:8000/translation_memory/?user_id=1' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjAyNDEyMjg1LCJqdGkiOiI3YjM5ZTcxODNjYTQ0MTVhODJiOWI5MjY1OTQxNWYzNiIsInVzZXJfaWQiOjF9.9itEwl_cLjV8YYuyQahV8qQlhkiQsB_HFb_9qGk4kVU' \
;

done;



http://127.0.0.1:8000/translation_memory/?user_id=1




for i in {1..100}; do
curl --location --request POST 'http://127.0.0.1:8000/get_corpus_by_phrase/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjAyNDEyMjg1LCJqdGkiOiI3YjM5ZTcxODNjYTQ0MTVhODJiOWI5MjY1OTQxNWYzNiIsInVzZXJfaWQiOjF9.9itEwl_cLjV8YYuyQahV8qQlhkiQsB_HFb_9qGk4kVU' \
--data-raw '{
  "phrase": "love",
  "user_id": 1
}
';
done;


for i in {1..100}; do
curl --location --request POST 'http://127.0.0.1:8000/get_corpus_by_phrase/' \
--header 'Content-Type: application/json' \
--data-raw '{
  "phrase": "love",
  "user_id": 1
}
';
done;