###
GET http://127.0.0.1:8000/translation_memory/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
###
GET http://127.0.0.1:8000/translation_memory/?user_id=1
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
###
GET http://127.0.0.1:8000/translation_memory/1
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466
###
POST http://127.0.0.1:8000/translation_memory/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "Default translation memory 1",
  "description": "Đây là TM mặc định, bất kỳ ai cũng có thể truy cập",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
}

###
POST http://127.0.0.1:8000/translation_memory/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "Khoa học tự nhiên",
  "description": "gồm các TM thuộc lĩnh vực khoa học tự nhiên",
  "src_lang": "en",
  "tar_lang": "vi",
  "user": 1,
}


###
PUT http://127.0.0.1:8000/translation_memory/3/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466

{
  "name": "TM3 updated",
  "description": "des updated",
  "src_lang": "phil",
  "tar_lang": "en",
  "user": 1
}

###
DELETE http://127.0.0.1:8000/translation_memory/13/
Content-Type: application/json
Authorization: token 40877ca59cefde907ef9d6db37c5ec253d98b466