###
GET http://127.0.0.1:8000/translation_memories/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
###
GET http://127.0.0.1:8000/translation_memories/1
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
###
POST http://127.0.0.1:8000/translation_memories/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
{
    "name": "TM3",
    "description": "des",
    "src_lang": "ja",
    "tar_lang": "vi",
    "user": 1
}

###
PUT http://127.0.0.1:8000/translation_memories/3/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732
{
    "name": "TM3 updated",
    "description": "des updated",
    "src_lang": "phil",
    "tar_lang": "en",
    "user": 1
}

###
DELETE http://127.0.0.1:8000/translation_memories/13/
Content-Type: application/json
Authorization: token 2ecf7eb2a7e50f8f63dd7fc19c890eecf8c3c732