
# SIGN UP
POST http://127.0.0.1:8000/sign_up/ 
Content-Type: application/json

{
    "username": "chinh",
    "email": "chinhguitar@gmail.com",
    "password": "123456789"
}

###
# SIGN IN
POST http://127.0.0.1:8000/get-token/ 
Content-Type: application/json


{
    "username": "chinh",
    "password": "123456789"
}

###

# USER 2
# SIGN UP
POST http://127.0.0.1:8000/sign_up/ 
Content-Type: application/json

{
    "username": "trung",
    "email": "trungguitar@gmail.com",
    "password": "123456789"
}

###
# SIGN IN
POST http://127.0.0.1:8000/get-token/ 
Content-Type: application/json


{
    "username": "trung",
    "password": "123456789"
}
