# Generated by Django 2.2.12 on 2020-10-03 14:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='translate_service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gt', 'Google Translate'), ('mm', 'My Memory'), ('onmt', 'Open NMT')], max_length=200),
        ),
    ]
