# Generated by Django 3.0.4 on 2020-07-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glossarycontent',
            unique_together={('src_phrase', 'tar_phrase', 'glossary')},
        ),
        migrations.AlterUniqueTogether(
            name='tmcontent',
            unique_together={('src_sentence', 'tar_sentence', 'translation_memory')},
        ),
    ]
