# Generated by Django 3.0.4 on 2020-07-27 10:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='src_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='tar_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='src_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='tar_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='translate_service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gt', 'Google Translate'), ('mm', 'My Memory')], max_length=5),
        ),
        migrations.AlterField(
            model_name='translationmemory',
            name='src_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='translationmemory',
            name='tar_lang',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=2),
        ),
    ]
