# Generated by Django 3.0.4 on 2020-06-18 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0002_auto_20200618_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='glossarytype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translationmemory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='glossary',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='glossarytype',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='translationmemory',
            unique_together={('name', 'user')},
        ),
    ]
