# Generated by Django 2.2.12 on 2020-10-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0002_auto_20201003_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_similarity_for_gloss', models.FloatField(default=0.8)),
                ('min_similarity_for_tm', models.FloatField(default=0.8)),
                ('similarity_type', models.CharField(choices=[('lev', 'Lexical Similarity: Levenshtein'), ('bert', 'Semantic Similarity: BERT Model')], default='lev', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
