# Generated by Django 2.2.12 on 2020-10-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='similarity_type',
            field=models.CharField(choices=[('lev', 'Lexical Similarity: Levenshtein'), ('bert', 'Semantic Similarity: BERT Model')], default='lev', max_length=20),
        ),
    ]
