# Generated by Django 3.0.4 on 2020-07-29 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0003_corpus_corpuscontent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpus',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='corpuscontent',
            unique_together={('corpus', 'phrase')},
        ),
    ]
