# Generated by Django 3.0.4 on 2020-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20200423_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
