# Generated by Django 2.2.12 on 2020-10-05 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0004_auto_20201005_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('user', 'min_similarity_for_gloss', 'min_similarity_for_tm', 'similarity_type')},
        ),
    ]
