# Generated by Django 3.0.4 on 2020-07-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20200729_0626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpus',
            unique_together=set(),
        ),
    ]
