# Generated by Django 2.2.12 on 2020-09-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20200729_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='insert_translation_memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_requests_insert', to='cat.TranslationMemory'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='tm_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.TMContent'),
        ),
    ]
