# Generated by Django 3.0.4 on 2020-04-25 14:39

import cat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20200423_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=cat.models.File.get_upload_path),
        ),
    ]
