# Generated by Django 2.2.12 on 2020-09-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20200912_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='insert_translation_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requests_insert', to='cat.TranslationMemory'),
        ),
    ]
