# Generated by Django 3.0.4 on 2020-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_auto_20200427_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='tag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='tar_str',
            field=models.TextField(blank=True),
        ),
    ]
