# Generated by Django 3.0.4 on 2020-04-30 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0008_auto_20200427_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='glossarytype',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='translationmemory',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='glossarycontent',
            unique_together={('src_phrase', 'tar_phrase')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tmcontent',
            unique_together={('src_sentence', 'tar_sentence')},
        ),
    ]
