# Generated by Django 3.0.4 on 2020-04-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_auto_20200430_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='Type',
            new_name='glossary_type',
        ),
    ]
