# Generated by Django 3.0.4 on 2020-04-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_auto_20200430_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='glossary_type',
            new_name='gloss_type',
        ),
    ]
