FROM chinhrb/clc_server:v7
ENV PYTHONUNBUFFERED=1 POSTGRES_PASSWORD=postgres@clc
WORKDIR /clc_server
# RUN git pull &&\
#     pip3 install -r requirements.txt &&\
#     python3 manage.py makemigrations &&\
#     python3 manage.py migrate